kerberos:
  key: RANDOM
  password: RANDOM
ambari:
  adminPassword: RANDOM  
credentialName: sball-se

nifi:
  security:
    encrypt:
      configuration:
        password: RANDOM
  sensitive:
    props:
      key: RANDOM
  toolkit:
    tls:
      token: RANDOM
  registry:
    security:
      encrypt:
        configuration:
          password: RANDOM
    sensitive:
      props:
        key: RANDOM

ranger:
  kms:
    password: RANDOM